name = "Cobbleverse"
author = "Jenaru0"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b1df9f5a567ef6f6d4075d046cd54a9bc390fdd8f842d562c3fd8199f0d32b3"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
