name = "Cobbleverse"
author = "Jenaru0"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f096dee3a2d487a0ec263d5a646feb0b3e6b6a4fd3af95d9d798b1000e985a4f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
